[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"lxml==4.9.2",
	"pandas==2.0.3",
]

[project.optional-dependencies]
dev = [
	"black==23.7.0",
	"mypy==1.4.1",
	"ruff==0.0.282",
	"ssort==0.11.6",
]
