[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"lxml==4.9.2",
	"pandas==2.0.2",
]

[project.optional-dependencies]
dev = [
	"black==23.3.0",
	"mypy==1.4.0",
	"ruff==0.0.274",
	"ssort==0.11.6",
]
