[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"lxml==4.9.2",
	"pandas==2.1.1",
]

[project.optional-dependencies]
dev = [
	"black==23.9.1",
	"djlint==1.34.0",
	"mypy==1.5.1",
	"ruff==0.0.291",
	"ssort==0.11.6",
]
