[project]
name = "UNKNOWN"
version = "0.0.0"
dependencies = [
	"playwright==1.35.0",
	"pydicom==2.4.1",
]

[project.optional-dependencies]
dev = [
	"black==23.3.0",
	"mypy==1.4.1",
	"ruff==0.0.277",
	"ssort==0.11.6",
]
