on: [push, pull_request]

jobs:
  make:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check code and build binaries for node.
        run: |
          make check
          make
      - name: Check code and build binaries for node.
        run: |
          make -C docs/node/ check
          make -C docs/node/
      - name: Check code and build binaries for browser.
        run: |
          make -C docs/ check
          make -C docs/
